// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package postgres

import (
	"database/sql"
)

type Event struct {
	ID           int32
	Name         string
	Description  sql.NullString
	Issuer       sql.NullInt32
	StartingAt   sql.NullTime
	EndingAt     sql.NullTime
	MaxAmount    sql.NullInt32
	MaxPerPerson sql.NullInt32
}

type Offer struct {
	ID     int32
	Issuer sql.NullInt32
	Amount int32
}

type Tab struct {
	ID     int32
	UserID sql.NullInt32
	Amount int32
	At     sql.NullTime
}

type User struct {
	ID       int32
	Username sql.NullString
	Email    string
	Credit   sql.NullInt32
}
